name: Deploy Front to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Opcional: Build local para verificar erros antes do deploy
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build (opcional)
        run: |
          docker build -t musicoson-web-test .

      # Deploy na VPS
      - name: Execute deploy.sh via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/musicoson-web
            git pull origin main  # Garante que a VPS tem o código mais recente
            chmod +x ./scripts/deploy.sh  # Assegura permissões
            ./scripts/deploy.sh